using System.Drawing;using System.Windows.Forms;namespace STAR.Forms{public class Base:Form{protected Color Gold=Color.FromArgb(212,175,55);protected Base(){BackColor=Color.FromArgb(12,12,12);ForeColor=Color.White;Font=new Font("Segoe UI",10);StartPosition=FormStartPosition.CenterScreen;Width=900;Height=600;}protected Button B(string t,int x,int y){var b=new Button{Text=t,Location=new Point(x,y),Width=180,Height=40,BackColor=Gold,ForeColor=Color.Black,FlatStyle=FlatStyle.Flat};Controls.Add(b);return b;}protected void Title(string t){Controls.Add(new Label{Text="★ STAR  |  "+t,ForeColor=Gold,Font=new Font("Segoe UI",22,FontStyle.Bold),AutoSize=true,Location=new Point(25,20)});}}
public class SplashForm:Base{public SplashForm(){Width=500;Height=350;Title("Welcome");var timer=new Timer{Interval=1500};timer.Tick+=(s,e)=>{timer.Stop();new LoginForm().Show();Hide();};timer.Start();}}
public class LoginForm:Base{TextBox u=new(){Location=new Point(300,150),Width=300};TextBox p=new(){Location=new Point(300,210),Width=300,UseSystemPasswordChar=true};public LoginForm(){Title("Login");Controls.AddRange(new Control[]{new Label{Text="Email or Username",Location=new Point(150,155),AutoSize=true},u,new Label{Text="Password",Location=new Point(150,215),AutoSize=true},p});B("Login",300,270).Click+=(s,e)=>{if(u.Text==""||p.Text==""){MessageBox.Show("Complete all fields");return;}new HomeForm().Show();Hide();};B("Create Account",300,330).Click+=(s,e)=>{new RegisterForm().Show();Hide();};B("Forgot Password",300,390).Click+=(s,e)=>{new ForgotPasswordForm().Show();Hide();};}}
public class RegisterForm:Base{public RegisterForm(){Title("Register");var n=new TextBox{Location=new Point(250,130),Width=350};var e=new TextBox{Location=new Point(250,190),Width=350};var p=new TextBox{Location=new Point(250,250),Width=350,UseSystemPasswordChar=true};Controls.AddRange(new Control[]{new Label{Text="Full name",Location=new Point(120,135),AutoSize=true},n,new Label{Text="Email",Location=new Point(120,195),AutoSize=true},e,new Label{Text="Password",Location=new Point(120,255),AutoSize=true},p});B("Register",250,330).Click+=(s,x)=>{if(n.Text==""||e.Text==""||p.Text==""){MessageBox.Show("Required fields missing");return;}MessageBox.Show("Registration successful");new LoginForm().Show();Hide();};}}
public class ForgotPasswordForm:Base{public ForgotPasswordForm(){Title("Forgot Password");B("Verify and Reset",300,180).Click+=(s,e)=>MessageBox.Show("Verification started");B("Back",300,240).Click+=(s,e)=>{new LoginForm().Show();Hide();};}}
public class VerificationForm:Base{public VerificationForm(){Title("Verification");B("Verify",300,200).Click+=(s,e)=>new HomeForm().Show();}}
public class HomeForm:Base{public HomeForm(){Title("Home");B("Create Post",40,100).Click+=(s,e)=>new CreatePostForm().Show();B("Stories",40,155).Click+=(s,e)=>new StoriesForm().Show();B("Search",40,210).Click+=(s,e)=>new SearchForm().Show();B("Messages",40,265).Click+=(s,e)=>new ChatListForm().Show();B("Profile",40,320).Click+=(s,e)=>new ProfileForm().Show();B("Notifications",40,375).Click+=(s,e)=>new NotificationsForm().Show();B("Settings",40,430).Click+=(s,e)=>new SettingsForm().Show();Controls.Add(new Label{Text="Your STAR feed",ForeColor=Gold,Font=new Font("Segoe UI",20),Location=new Point(350,150),AutoSize=true});}}
public class CreatePostForm:Base{public CreatePostForm(){Title("Create Post");B("Publish",350,200).Click+=(s,e)=>MessageBox.Show("Post published successfully");}}
public class PostDetailsForm:Base{public PostDetailsForm(){Title("Post Details");B("Like",250,200);B("Comment",450,200);}}
public class StoriesForm:Base{public StoriesForm(){Title("Stories");B("Create Story",350,150).Click+=(s,e)=>new CreateStoryForm().Show();}}
public class CreateStoryForm:Base{public CreateStoryForm(){Title("Create Story");B("Publish",350,200).Click+=(s,e)=>MessageBox.Show("Story published successfully");}}
public class SearchForm:Base{public SearchForm(){Title("Search");B("Search Users and Posts",300,180);}}
public class ProfileForm:Base{public ProfileForm(){Title("Profile");B("Edit Profile",350,150).Click+=(s,e)=>new EditProfileForm().Show();B("Followers",350,210).Click+=(s,e)=>new FollowersForm().Show();B("Following",350,270).Click+=(s,e)=>new FollowingForm().Show();}}
public class EditProfileForm:Base{public EditProfileForm(){Title("Edit Profile");B("Save Changes",350,200).Click+=(s,e)=>MessageBox.Show("Profile saved");}}
public class FollowersForm:Base{public FollowersForm(){Title("Followers");}}
public class FollowingForm:Base{public FollowingForm(){Title("Following");}}
public class ChatListForm:Base{public ChatListForm(){Title("Messages");B("Open Conversation",350,180).Click+=(s,e)=>new ChatForm().Show();}}
public class ChatForm:Base{public ChatForm(){Title("Chat");B("Send Message",350,200);B("Voice Call",350,260).Click+=(s,e)=>new VoiceCallForm().Show();B("Video Call",350,320).Click+=(s,e)=>new VideoCallForm().Show();}}
public class VoiceCallForm:Base{public VoiceCallForm(){Title("Voice Call");B("Accept",250,220);B("End Call",450,220);}}
public class VideoCallForm:Base{public VideoCallForm(){Title("Video Call");B("Microphone",200,400);B("Camera",400,400);B("End Call",600,400);}}
public class NotificationsForm:Base{public NotificationsForm(){Title("Notifications");}}
public class LikesForm:Base{public LikesForm(){Title("Likes");}}
public class SavedPostsForm:Base{public SavedPostsForm(){Title("Saved Posts");}}
public class SettingsForm:Base{public SettingsForm(){Title("Settings");B("Privacy",250,120).Click+=(s,e)=>new PrivacyForm().Show();B("Security",450,120).Click+=(s,e)=>new SecurityForm().Show();B("Appearance",250,180).Click+=(s,e)=>new AppearanceForm().Show();B("Activity",450,180).Click+=(s,e)=>new ActivityForm().Show();B("Achievements",250,240).Click+=(s,e)=>new AchievementsForm().Show();B("Leaderboard",450,240).Click+=(s,e)=>new LeaderboardForm().Show();B("About",350,300).Click+=(s,e)=>new AboutForm().Show();}}
public class PrivacyForm:Base{public PrivacyForm(){Title("Privacy");B("Save Settings",350,200).Click+=(s,e)=>MessageBox.Show("Privacy settings saved");}}
public class SecurityForm:Base{public SecurityForm(){Title("Security");B("Change Password",350,200).Click+=(s,e)=>MessageBox.Show("Password changed");}}
public class AppearanceForm:Base{public AppearanceForm(){Title("Appearance");B("Save Appearance",350,200).Click+=(s,e)=>MessageBox.Show("Appearance saved");}}
public class ActivityForm:Base{public ActivityForm(){Title("Activity");}}
public class AchievementsForm:Base{public AchievementsForm(){Title("Achievements");}}
public class LeaderboardForm:Base{public LeaderboardForm(){Title("Leaderboard");}}
public class AboutForm:Base{public AboutForm(){Title("About");Controls.Add(new Label{Text="STAR\nSocial Media Application\nVersion 1.0\nUniversity software engineering project",Location=new Point(300,150),AutoSize=true,ForeColor=Color.White});}}
}
